apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: py-mtls-frontend:case3
        imagePullPolicy: Never
        env:
        - name: USE_MTLS
          value: "true"      # <-- toggle this true/false for demo
        - name: BACKEND_HOST
          value: "backend-svc"
        - name: BACKEND_PORT
          value: "8080"      # <-- backend listens on 8080 internally
        - name: CERT_PATH
          value: "/etc/tls/tls.crt"
        - name: KEY_PATH
          value: "/etc/tls/tls.key"
        - name: CA_PATH
          value: "/etc/tls/ca.crt"
        volumeMounts:
        - name: certs
          mountPath: "/etc/tls"
          readOnly: true
      volumes:
      - name: certs
        csi:
          driver: csi.cert-manager.io
          readOnly: true
          volumeAttributes:
            csi.cert-manager.io/issuer-name: demo-ca
            csi.cert-manager.io/issuer-kind: Issuer
            csi.cert-manager.io/common-name: frontend-app
            csi.cert-manager.io/duration: 1m
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    app: frontend 
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
